//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class marksheet
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int EnglishMark { get; set; }
        public int MathMark { get; set; }
        public int UrduMark { get; set; }
        public int TotalMark { get; set; }
        public int ObtainMark { get; set; }
        public double Percentages { get; set; }
        public string Grade { get; set; }
    }
}
